<?php

/**
 * Main module file for SP Beltool csv importer.
 */

module_load_include('inc', 'spbellen', 'includes/spbellen_import');
module_load_include("inc", "spbellen_csv_import", "spbellen_csv_import");

/**
 * Implements hook_spbellen_importer_info().
 */
function spbellen_csv_import_spbellen_importer_info() {
  $importer_info = array(
    'form_definition_function' => 'spbellen_csv_import_import_form',
    'form_validation_function' => 'spbellen_csv_import_import_form_validate',
    'form_submit_function' => 'spbellen_csv_import_import_form_submit',
    'importer_source_title' => 'CSV',

  );
  return $importer_info;
}

/**
 * Civi importer form definition.
 */
function spbellen_csv_import_import_form(&$form, &$form_state) {
  $storage = &$form_state['storage'];

  $form['csv_import_file_select'] = array(
    '#type' => 'fieldset',
    '#title' => 'Selecteer een csv bestand',
    '#prefix' => '<div id="spbellen_csv_import_ajax_form">',
    '#suffix' => '</div>',
  );

  // Upload file.
  // ----------------------------------------------------------
  if (empty($storage['upload'])) {
    // Set the encoding type (necessary for file uploads).
    $form['#attributes']['enctype'] = 'multipart/form-data';

    $form['csv_import_file_select']['upload'] = array(
      '#type' => 'file',
      '#title' => 'CSV bestand',
      '#disabled' => (empty($storage['upload'])) ? FALSE : TRUE,
    );

    $form['csv_import_file_select']['submit_file'] = array(
      '#type' => 'submit',
      '#name' => 'submit_file',
      '#value' => 'Verder',
      '#ajax' => array(
        'wrapper' => 'spbellen_csv_import_ajax_form',
        'callback' => 'spbellen_csv_import_form_ajax_callback',
      ),
    );
  }
  else {
    if ($storage['delimiter'] !== FALSE) {
      $delimiter = ($storage['delimiter'] === "\t") ? 'tab' : $storage['delimiter'];
      if (!empty($delimiter)) {
        $form['csv_import_file_select']['selected_file'] = array(
          '#markup' => '<p>Bestand: ' . $storage['upload']->filename . '<br/>' . 'Veldscheidingsteken: "' . $delimiter . '"</p>',
        );
      }
    }
    $form['csv_import_file_select']['table_start'] = array(
      '#markup' => '<table><tr><th>csv veld waarden</th><th>beltool velden</th>',
    );
    $options = spbellen_contact_fields();
    if (empty($storage['contact_fields'])) {
      $storage['contact_fields'] = $options;
    }
    $default = '';
    foreach ($storage['csv_field_mapping_data'] as $csv_field_key => $example_values) {
      $form['csv_import_file_select']['csv_field_key_' . $csv_field_key] = array(
        '#type' => 'select',
        '#options' => $options,
        '#empty_option' => '- Geen -',
        '#default_value' => $default,
        '#name' => 'csv_field_key_' . $csv_field_key,
        '#prefix' => '<tr><td><p>' . implode('<br/>', $example_values) . '</p></td><td>',
        '#suffix' => '</td>',
        '#ajax' => array(
          'wrapper' => 'spbellen_csv_import_ajax_form',
          'callback' => 'spbellen_csv_import_form_ajax_callback',
        ),
      );
    }
    $form['csv_import_file_select']['table_end'] = array(
      '#markup' => '</table>',
    );

    $form['csv_import_file_select']['skip_first_row'] = array(
      '#title' => 'Eerste rij?',
      '#type' => 'checkboxes',
      '#options' => array('skip_first_row' => 'overslaan'),
      '#multiple' => TRUE,
    );

  }
}

/**
 * Civi Import validation function.
 */
function spbellen_csv_import_import_form_validate($form, &$form_state) {
  $values = $form_state['values'];
  $storage = &$form_state['storage'];

  if (!empty($form_state['triggering_element']['#name'])) {
    // Check fixed name buttons.
    $trigger = $form_state['triggering_element']['#name'];
    switch ($trigger) {
      case 'submit_file':
        $file = file_save_upload('upload', array('file_validate_extensions' => array('csv tsv txt')));
        if ($file) {
          // Move the file into the Drupal file system.
          if ($file = file_move($file, 'private://')) {
            // Get delimiter.
            $delimiter = spbellen_csv_import_detect_delimiter($file);
            if ($delimiter === FALSE) {
              form_set_error('file', 'Het veldscheidingsteken kon niet worden gedetecteerd.');
            }
            else {
              // Save the file for use in the submit handler.
              $storage['upload'] = $file;
              $storage['delimiter'] = $delimiter;
              // Save csv field data.
              $storage['csv_field_mapping_data'] = spbellen_csv_import_parse_csv_field_mapping_data($file, $delimiter);
            }
          }
          else {
            form_set_error('file', t("Failed to write the uploaded file to the site's file folder."));
          }
        }
        else {
          form_set_error('file', t('No file was uploaded.'));
        }
        return;

      case 'import_submit':
        if (!empty($storage['upload'])) {
          $storage['skip_first_row'] = (reset($values['skip_first_row']) === 'skip_first_row') ? 1 : 0;
          // Store mapping.
          foreach ($values as $key => $value) {
            preg_match('/^csv_field_key_([0-9]+)$/', $key, $matches);
            if (isset($matches[1])) {
              if (!empty($values[$matches[0]])) {
                $storage['csv_beltool_mapping'][$matches[1]] = $values[$matches[0]];
              }
            }
          }
          if (empty($storage['csv_beltool_mapping']) || array_search('phone', $storage['csv_beltool_mapping']) === FALSE) {
            form_set_error('csv_import_file_select', 'Geef aan welk csv veld het telefoonnummer bevat!');
          }
        }
        break;
    }
  }
}

/**
 * Csv Import submit function.
 */
function spbellen_csv_import_import_form_submit($form, &$form_state) {
  $storage = &$form_state['storage'];

  if (!empty($form_state['triggering_element']['#name'])) {
    $trigger = $form_state['triggering_element']['#name'];
    switch ($trigger) {
      case 'submit_file':
        $form_state['rebuild'] = TRUE;
        break;

      case 'import_submit':
        if (!empty($storage['upload']) && !empty($storage['csv_beltool_mapping'])) {
          // Create import.
          $filename = $storage['upload']->filename;
          $group_title = $filename;

          $group_id = spbellen_import_merge_group('spbellen_csv_import', $filename, $group_title);
          $import_id = spbellen_import_insert_import($group_id);
          spbellen_import_insert_group_campaign_relation($group_id, $storage['campaign']);

          $storage['group_title'] = $group_title;
          $storage['group_id'] = $group_id;
          $storage['import_id'] = $import_id;

          // Import csv.
          $batch = array(
            'operations' => array(
              array('spbellen_csv_import_batch', array($storage)),
            ),
            'finished' => 'spbellen_csv_import_batch_finished',
            'title' => 'Importeren csv',
            'init_message' => '0',
            'progress_message' => '',
            'error_message' => 'Er is een fout opgetreden bij het ophalen van data',
          );
          batch_set($batch);
          return;
        }
        break;
    }
  }
}

/**
 * Civi Import ajax callback function.
 */
function spbellen_csv_import_form_ajax_callback($form, &$form_state) {
  return $form['csv_import_file_select'];
}
