<?php

/**
 * Main module file for SP Beltool Civi importer.
 */

module_load_include('inc', 'spbellen', 'includes/spbellen_import');
module_load_include("inc", "spbellen_civi_import", "spbellen_civi_import");

 /**
  * Implements hook_menu().
  */
function spbellen_civi_import_menu() {
  $items = array();
  $items['spbellen/group/autocomplete/%'] = array(
    'title' => 'SP bellen autocomplete',
    'page callback' => 'spbellen_civi_import_group_autocomplete',
    'page arguments' => array(3),
    'access arguments' => array('spbellen administer campaigns'),
    'type' => MENU_CALLBACK,
    'file' => 'spbellen_civi_import.inc',
  );
  return $items;
}

/**
 * Implements hook_spbellen_importer_info().
 */
function spbellen_civi_import_spbellen_importer_info() {
  $importer_info = array(
    'form_definition_function' => 'spbellen_civi_import_import_form',
    'form_validation_function' => 'spbellen_civi_import_import_form_validate',
    'form_submit_function' => 'spbellen_civi_import_import_form_submit',
    'auto_import' => TRUE,
    'importer_source_title' => 'CiviCRM',
    'import_function' => 'spbellen_civi_import_drush_import',
  );
  return $importer_info;
}

/**
 * Implements hook_spbellen_importer_info() form_definition_function.
 */
function spbellen_civi_import_import_form(&$form, &$form_state) {
  $form_state['civi_groups'] = spbellen_civi_import_get_groups();
  $storage = &$form_state['storage'];

  $form['civi_group_select'] = array(
    '#type' => 'fieldset',
    '#title' => 'Selecteer CiviCRM groepen',
    '#prefix' => '<div id="spbellen_civi_import_ajax_form">',
    '#suffix' => '</div>',
  );

  // Show message.
  $form['civi_group_select']['message_cache'] = array(
    '#markup' => '<p><strong>Leeg de Drupal cache als een CiviCRM groep niet te vinden is!</strong></p>',
  );

  // Show stored groups.
  if (!empty($storage['groups'])) {
    $markup = '<p><strong>Geselecteerde groepen:</strong><br/>';
    $form['civi_group_select']['selected_groups'] = array(
      '#markup' => $markup,
    );
    foreach ($storage['groups'] as $group_key => $group_name) {
      $form['civi_group_select']['del_group_' . $group_key] = array(
        '#type' => 'button',
        '#name' => 'del_group_' . $group_key,
        '#value' => 'x',
        '#suffix' => ' ' . $group_name . '<br/>',
        '#ajax' => array(
          'wrapper' => 'spbellen_civi_import_ajax_form',
          'callback' => 'spbellen_civi_import_form_ajax_callback',
          '#default_value' => empty($storage['groups']) ? array() : $storage['groups'],
        ),
      );
    }
  }
  $form['civi_group_select']['group'] = array(
    '#type' => 'textfield',
    '#title' => 'Selecteer een groep',
    '#description' => 'Geen selectie van CiviCRM smart mogelijk ivm. batch import!',
    '#autocomplete_path' => 'spbellen/group/autocomplete/all_but_smart',
  );

  $form['civi_group_select']['add_group'] = array(
    '#type' => 'button',
    '#value' => 'Voeg toe',
    '#name' => 'add_group',
    '#ajax' => array(
      'wrapper' => 'spbellen_civi_import_ajax_form',
      'callback' => 'spbellen_civi_import_form_ajax_callback',
    ),
  );
}

/**
 * Implements hook_spbellen_importer_info() form_validation_function.
 */
function spbellen_civi_import_import_form_validate($form, &$form_state) {
  $values = $form_state['values'];
  $storage = &$form_state['storage'];

  if (!empty($form_state['triggering_element']['#name'])) {
    // Check fixed name buttons.
    $trigger = $form_state['triggering_element']['#name'];
    switch ($trigger) {
      case 'add_group':
        $civi_groups = $form_state['civi_groups'];
        $group_raw = $values['group'];
        $group = spbellen_parse_id_from_select_value($group_raw);
        if (!empty($group)) {
          $storage['groups'][$group] = $civi_groups[$group];
          $form_state['input']['group'] = '';
        }
        else {
          form_set_error('group', 'Selecteer eerst een doelgroep');
        }
        break;

    }

    // Delete buttons.
    preg_match('/^del_group_([0-9]+)$/', $trigger, $matches);
    if (!empty($matches[1])) {
      unset($storage['groups'][$matches[1]]);
    }
  }
}

/**
 * Implements hook_spbellen_importer_info() form_submit_function.
 */
function spbellen_civi_import_import_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  $storage = $form_state['storage'];

  if (!empty($storage['groups']) && !empty($storage['campaign'])) {
    // Import contacts.
    $operations = array();
    $civi_groups = $storage['groups'];
    $batch = spbellen_civi_import_import_groups($civi_groups, $storage['campaign']);
    if (!empty($batch)) {
      batch_set($batch);
    }
    return;
  }
  drupal_set_message('Er is iets misgegaan bij het importeren, probeer het opnieuw.', 'error');
}

/**
 * Civi Import ajax callback function.
 */
function spbellen_civi_import_form_ajax_callback($form, &$form_state) {
  return $form['civi_group_select'];
}

/**
 * Implements hook_spbellen_get_chapter_and_region().
 */
function spbellen_civi_import_spbellen_get_chapter_and_region($postal_code) {
  set_time_limit(0);
  $spcivi = \SPCivi::getInstance();
  $params = array(
    'name' => $postal_code,
    'api.Relationship.getsingle' => array('contact_id_a' => '$value.id', 'relationship_type_id' => 93),
    'api.Contact.getsingle' => array('id' => '$value.api.Relationship.getsingle.contact_id_b'),
  );
  $result = $spcivi->api('Geostelsel', 'getafdeling', $params);
  if (spbellen_check_result($result, 'afdelingsinformatie', 'getsingle', $params)) {
    if (!empty($result['values'])) {
      $data_raw = array_shift($result['values']);
      if (!empty($data_raw['id'])) {
        $data['afdeling_id'] = $data_raw['id'];
        $data['afdeling'] = $data_raw['display_name'];
        if (!empty($data_raw['api.Contact.getsingle'])) {
          $data['regio_id'] = $data_raw['api.Contact.getsingle']['contact_id'];
          $data['regio'] = $data_raw['api.Contact.getsingle']['display_name'];
        }
      }
      return $data;
    }
  }
}

/**
 * Implements hook_spbellen_process_phone_invalid.
 */
function spbellen_civi_import_spbellen_process_phone_invalid($contact_data) {

  // If crm contact id is set, remove phone number from civi.
  if (!empty($contact_data['phone']) && !empty($contact_data['crm_contact_id'])) {
    try {
      set_time_limit(20);
      $spcivi = \SPCivi::getInstance();
      // Get contact phone numbers.
      $params = array(
        'return' => "id",
        'id' => $contact_data['crm_contact_id'],
        'api.Phone.get' => array(),
      );
      $result = $spcivi->api('Contact', 'get', $params);
      if (spbellen_check_result($result, 'een contact', 'getsingle', $params)) {
        $phone_result = array_pop($result['values']);
        if (!empty($phone_result['api.Phone.get']) && !empty($phone_result['api.Phone.get']['values'])) {
          // Remove phone if found.
          foreach ($phone_result['api.Phone.get']['values'] as $phone_data) {
            if ($phone_data['phone_numeric'] == $contact_data['phone']) {
              // Remove phone number from contact.
              $params = array(
                'id' => $phone_data['id'],
              );
              $phone_del_result = $spcivi->api('Phone', 'delete', $params);
              if (spbellen_check_result($phone_del_result, 'een telefoonnummer', 'delete', $params)) {
                if (!empty($phone_del_result['values'])) {
                  watchdog('spbellen', 'Telefoonnummer ' . $contact_data['phone'] . ' verwijderd van contact ' . $contact_data['crm_contact_id'] . '.');
                  //spbellen_civi_import_create_activity($contact_data['crm_contact_id'], 'Controle wijziging contact via website', 'Dev', 'Telefoonnummer verwijderd van contact nr. ', $contact_data['crm_contact_id'], 'geen debug info');
                }
              }
            }
          }
        }
      }
    }
    catch(Exception $e){
      // Do nothing.
      watchdog('spbellen_civi_import', 'Er is een fout opgetreden bij het verwijderen van een telefoonnummer in CiviCRM. Foutmelding: '. $e);
    }
  }
}

/**
 * Implements hook_spbellen_crm_block_phone().
 */
function spbellen_civi_import_spbellen_crm_block_phone($crm_contact_id) {
  set_time_limit(0);
  $spcivi = \SPCivi::getInstance();
  $params = array(
    'id' => $crm_contact_id,
    'do_not_phone' => 1,
  );
  $result = $spcivi->api('Contact', 'create', $params);
  if (spbellen_check_result($result, 'een contact', 'create', $params)) {
    watchdog('spbellen', 'CiviCRM contact nr. ' . $crm_contact_id . ' privacy instelling "Niet bellen" ingeschakeld.');
  }
}

/**
 * Drush import groups.
 */
function spbellen_civi_import_drush_import() {
  // Get CiviCRM groups to import.
  $civi_groups = array();
  $query = "SELECT title, external_group_id FROM {spbellen_groups} WHERE auto_import = 1 AND importer = 'spbellen_civi_import'";
  $result = db_query($query);
  if ($result) {
    while ($row = $result->fetchAssoc()) {
      $civi_group_id = $row['external_group_id'];
      if (!empty($civi_group_id)) {
        $civi_groups[$civi_group_id] = '';
      }
    }
  }
  if (!empty($civi_groups)) {
    // Import groups.
    $batch = spbellen_civi_import_import_groups($civi_groups);
    if (!empty($batch)) {
      $batch['progressive'] = FALSE;
      batch_set($batch);
      $batch =& batch_get();
      // Process the batch.
      drush_backend_batch_process();
    }
  }
}

/**
 * Import contacts from Civi groups.
 * @param  array $civi_groups key is CiviCRM group id, value is group name.
 */
function spbellen_civi_import_import_groups($civi_groups, $campaign_id = NULL) {
  if (!empty($civi_groups)) {
    // Initialize CiviCRM api.
    set_time_limit(0);
    $spcivi = \SPCivi::getInstance();
    // Creae batch operations.
    foreach ($civi_groups as $civi_group_id => $civi_group_title) {
      // Get last imported id from group.
      $last_imported_id = spbellen_import_get_last_imported($civi_group_id);
      // Check if there are new contacts to be imported in the group.
      $params = array(
        'group' => $civi_group_id,
        'get_count' => 1,
        'group_contact_id_offset' => $last_imported_id,
      );
      $results = $spcivi->api('Contact', 'getbeltooldata', $params);
      if (spbellen_check_result($results, 'contacten', 'get', $params)) {
        $number_of_contacts = $results['values'][0]['count'];
      }

      if (!empty($number_of_contacts)) {
        $civi_group_name = spbellen_civi_import_get_group_machine_name($civi_group_id);
        $group_id = spbellen_import_merge_group('spbellen_civi_import', $civi_group_id, $civi_group_title);
        $import_id = spbellen_import_insert_import($group_id);
        if (!empty($campaign_id)) {
          spbellen_import_insert_group_campaign_relation($group_id, $campaign_id);
        }

        if (!empty($civi_group_name)) {
          $import_data = array(
            'group_id' => $group_id,
            'import_id' => $import_id,
            'civi_group_id' => $civi_group_id,
            'civi_group_name' => $civi_group_name,
            'last_imported_id' => $last_imported_id,
            'number_of_contacts' => $number_of_contacts,
          );
          // Add operation for each campaign group.
          $operations[] = array(
            'spbellen_civi_import_get_targets_batch',
            array(
              $import_data,
            ),
          );
        }
      }
    }
    if (!empty($operations)) {
      $batch = array(
        'operations' => $operations,
        'finished' => 'spbellen_civi_import_get_targets_batch_finished',
        'title' => 'Ophalen contacten',
        'init_message' => '0',
        'progress_message' => 'Groep @current van @total',
        'error_message' => 'Er is een fout opgetreden bij het ophalen van contacten',
      );
      return $batch;
    }
    else {
      drupal_set_message('Er zijn geen nieuwe civicrm contacten gevonden om te importeren.');
    }
  }
}
